# Generated by Django 4.1.7 on 2023-03-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(default=234, max_length=30),
            preserve_default=False,
        ),
    ]
