# Generated by Django 4.1.7 on 2023-03-16 13:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=core.models.product_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
