# Generated by Django 4.1.7 on 2023-03-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_description_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ordered',
            field=models.IntegerField(default=0),
        ),
    ]
