# Generated by Django 4.1.7 on 2023-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_ordered_subcategory_ordered_user_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='img/NA-removebg.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/NA-removebg.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default='img/NA-removebg.png', null=True, upload_to='images/'),
        ),
    ]
