# Generated by Django 4.1.7 on 2023-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/NA-removebg.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/NA-removebg.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/NA-removebg.png', null=True, upload_to='images/'),
        ),
    ]
