# Generated by Django 4.1.7 on 2023-03-19 21:15

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_address_product_state_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(default=core.models.order_id, max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('S', 'Success'), ('P', 'Pending'), ('C', 'Cancel')], max_length=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
        ),
    ]
