# Generated by Django 4.1.7 on 2023-03-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_product_price_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('P', 'Pending'), ('C', 'Cancel')], default='P', max_length=1),
        ),
    ]
