# Generated by Django 4.1.7 on 2023-03-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_order_product_order_total_price_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='price',
        ),
    ]
