# Generated by Django 4.1.7 on 2023-03-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_total_price_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
