# Generated by Django 4.1.7 on 2023-03-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_cart_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_ordered_at',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
